// Design size: 615x385
// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "cclass_chooser.h"
#include <stdio.h>

void CClass_Chooser::cb_carea_i(ColorBox* o, void*) {
  ccolor c = o->getColor();
double c1,c2,c3;
if(cc_sRGB.get(c,c1,c2,c3))
  sRGBGamut->show();
else
  sRGBGamut->hide();
char buf[1024];
snprintf(buf,sizeof(buf),"%.4g,%.4g,%.4g",c1,c2,c3);
sRGBOutput->value(buf);
snprintf(buf,sizeof(buf),"%02x%02x%02x",(int)round(c1*255),(int)round(c2*255),(int)round(c3*255));
swatch->color(fl_rgb_color(round(c1*255),round(c2*255),round(c3*255)),fl_rgb_color(round(c1*255),round(c2*255),round(c3*255)));
swatch->redraw();
HTMLOutput->value(buf);
if(o->ColorSpace()->get(c,c1,c2,c3))
  csGamut->show();
else
  csGamut->hide();
snprintf(buf,sizeof(buf),"%.3g,%.3g,%.3g",c1,c2,c3);
cOutput->value(buf);
do_callback();
}
void CClass_Chooser::cb_carea(ColorBox* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_carea_i(o,v);
}

void CClass_Chooser::cb_CIELuv_i(Fl_Menu_*, void*) {
  carea->setColorSpace(&cc_CIELuv);
cOutput->label(carea->ColorSpace()->axes());
carea->do_callback();
}
void CClass_Chooser::cb_CIELuv(Fl_Menu_* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_CIELuv_i(o,v);
}

void CClass_Chooser::cb_CIELAB_i(Fl_Menu_*, void*) {
  carea->setColorSpace(&cc_CIELAB);
cOutput->label(carea->ColorSpace()->axes());
carea->do_callback();
}
void CClass_Chooser::cb_CIELAB(Fl_Menu_* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_CIELAB_i(o,v);
}

void CClass_Chooser::cb_CIEXYZ_i(Fl_Menu_*, void*) {
  carea->setColorSpace(&cc_CIEXYZ);
cOutput->label(carea->ColorSpace()->axes());
carea->do_callback();
}
void CClass_Chooser::cb_CIEXYZ(Fl_Menu_* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_CIEXYZ_i(o,v);
}

void CClass_Chooser::cb_CIExyY_i(Fl_Menu_*, void*) {
  carea->setColorSpace(&cc_CIExyY);
cOutput->label(carea->ColorSpace()->axes());
carea->do_callback();
}
void CClass_Chooser::cb_CIExyY(Fl_Menu_* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_CIExyY_i(o,v);
}

void CClass_Chooser::cb_sRGB_i(Fl_Menu_*, void*) {
  carea->setColorSpace(&cc_sRGB);
cOutput->label(carea->ColorSpace()->axes());
carea->do_callback();
}
void CClass_Chooser::cb_sRGB(Fl_Menu_* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_sRGB_i(o,v);
}

Fl_Menu_Item CClass_Chooser::menu_cspace[] = {
 {"CIELuv", 0,  (Fl_Callback*)CClass_Chooser::cb_CIELuv, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CIELAB", 0,  (Fl_Callback*)CClass_Chooser::cb_CIELAB, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CIEXYZ", 0,  (Fl_Callback*)CClass_Chooser::cb_CIEXYZ, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CIExyY", 0,  (Fl_Callback*)CClass_Chooser::cb_CIExyY, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"sRGB", 0,  (Fl_Callback*)CClass_Chooser::cb_sRGB, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void CClass_Chooser::cb_Overscan_i(Fl_Value_Slider* o, void*) {
  carea->overscan = o->value();
carea->redraw();
}
void CClass_Chooser::cb_Overscan(Fl_Value_Slider* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_Overscan_i(o,v);
}

void CClass_Chooser::cb_cOutput_i(Fl_Input* o, void*) {
  double c1,c2,c3;
if(sscanf(o->value(),"%lf,%lf,%lf",&c1,&c2,&c3) == 3)
  {
    ccolor c;
    carea->ColorSpace()->set(c,c1,c2,c3);
    carea->setColor(c);
  }
  carea->do_callback();
}
void CClass_Chooser::cb_cOutput(Fl_Input* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_cOutput_i(o,v);
}

void CClass_Chooser::cb_sRGBOutput_i(Fl_Input* o, void*) {
  double c1,c2,c3;
if(sscanf(o->value(),"%lf,%lf,%lf",&c1,&c2,&c3) == 3)
  {
    ccolor c;
    cc_sRGB.set(c,c1,c2,c3);
    carea->setColor(c);
  }
  carea->do_callback();
}
void CClass_Chooser::cb_sRGBOutput(Fl_Input* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_sRGBOutput_i(o,v);
}

void CClass_Chooser::cb_HTMLOutput_i(Fl_Input* o, void*) {
  int i1,i2,i3;
double c1,c2,c3;
if(sscanf(o->value(),"%02x%02x%02x",&i1,&i2,&i3) == 3)
  {
    c1=i1/255.0; c2=i2/255.0; c3=i3/255.0;
    ccolor c;
    cc_sRGB.set(c,c1,c2,c3);
    carea->setColor(c);
  }
  carea->do_callback();
}
void CClass_Chooser::cb_HTMLOutput(Fl_Input* o, void* v) {
  ((CClass_Chooser*)(o->parent()->user_data()))->cb_HTMLOutput_i(o,v);
}

CClass_Chooser::CClass_Chooser(int xp, int yp, int wp, int hp, const char *namep) : Fl_Group(xp,yp,wp,hp,namep) {
  Fl_Group* w;
  { Fl_Group* o = g = new Fl_Group(0, 0, 615, 385);
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_FOREGROUND_COLOR);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    { ColorBox* o = carea = new ColorBox(180, 23, 435, 356, "Colors");
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)cb_carea);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      o->end();
    }
    { Fl_Choice* o = cspace = new Fl_Choice(90, 23, 85, 20, "Color Space");
      o->down_box(FL_BORDER_BOX);
      o->when(FL_WHEN_CHANGED);
      o->menu(menu_cspace);
    }
    { Fl_Value_Slider* o = new Fl_Value_Slider(0, 46, 175, 22, "Overscan");
      o->type(1);
      o->minimum(0.5);
      o->maximum(10);
      o->step(0.5);
      o->value(2);
      o->textsize(14);
      o->callback((Fl_Callback*)cb_Overscan);
    }
    { Fl_Input* o = cOutput = new Fl_Input(5, 103, 170, 25, "Lab");
      o->callback((Fl_Callback*)cb_cOutput);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Input* o = sRGBOutput = new Fl_Input(5, 148, 170, 25, "sRGB");
      o->callback((Fl_Callback*)cb_sRGBOutput);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Input* o = HTMLOutput = new Fl_Input(5, 193, 170, 25, "HTML");
      o->callback((Fl_Callback*)cb_HTMLOutput);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Output* o = sRGBGamut = new Fl_Output(5, 223, 170, 25);
      o->textcolor(1);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      o->value("Out of sRGB Gamut");
    }
    { Fl_Output* o = csGamut = new Fl_Output(5, 254, 170, 25);
      o->textcolor(1);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      o->value("Out of colorspace Gamut");
    }
    { Fl_Box* o = swatch = new Fl_Box(5, 284, 170, 96);
      o->box(FL_DOWN_BOX);
    }
    o->end();
  }
  g->position(x(),y());
carea->setColorSpace(&cc_CIELuv);
}

ccolor CClass_Chooser::getcolor() {
  return carea->selcolor;
}

CClass_Chooser_Window::CClass_Chooser_Window(int xp, int yp, int wp, int hp, const char *namep) : Fl_Double_Window(xp,yp,wp,hp,namep) {
  CClass_Chooser* w;
  { CClass_Chooser* o = c = new CClass_Chooser(0, 0, 615, 385);
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_FOREGROUND_COLOR);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    o->end();
  }
}
