// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "spynavigate_ui.h"

Fl_Double_Window *controls=(Fl_Double_Window *)0;

Fl_Output *pattern_box=(Fl_Output *)0;

Fl_Value_Output *xstartbox=(Fl_Value_Output *)0;

Fl_Value_Output *xincbox=(Fl_Value_Output *)0;

Fl_Value_Output *xendbox=(Fl_Value_Output *)0;

Fl_Value_Output *ystartbox=(Fl_Value_Output *)0;

Fl_Value_Output *yincbox=(Fl_Value_Output *)0;

Fl_Value_Output *yendbox=(Fl_Value_Output *)0;

Fl_Value_Output *x_box=(Fl_Value_Output *)0;

Fl_Value_Output *y_box=(Fl_Value_Output *)0;

Fl_Output *filename_box=(Fl_Output *)0;

Fl_Choice *cmapch=(Fl_Choice *)0;

Fl_Value_Input *output_counter=(Fl_Value_Input *)0;

ImageWindow *iw=(ImageWindow *)0;

Fl_Double_Window *xsecwin=(Fl_Double_Window *)0;

Fl_Choice *dim=(Fl_Choice *)0;

static void cb_dim(Fl_Choice*, void*) {
  load_mtx_cut();
}

Fl_Value_Input *indexbox=(Fl_Value_Input *)0;

static void cb_indexbox(Fl_Value_Input*, void*) {
  double val=indexbox->value();
if (val > indexbox->maximum()) val = indexbox->maximum();
else if (val < indexbox->minimum()) val = indexbox->minimum();
indexslider->value(val);
indexroller->value(val);
indexbox->value(val);
load_mtx_cut();
}

Fl_Slider *indexslider=(Fl_Slider *)0;

static void cb_indexslider(Fl_Slider* o, void*) {
  indexbox->value(((Fl_Valuator *)o)->value());
indexbox->do_callback();
}

Fl_Roller *indexroller=(Fl_Roller *)0;

static void cb_indexroller(Fl_Roller* o, void*) {
  indexbox->value(round(((Fl_Valuator *)o)->value()));
indexbox->do_callback();
}

static void cb_dismiss(Fl_Button*, void*) {
  xsecwin->hide();
}

Fl_Value_Input *datamax_box=(Fl_Value_Input *)0;

static void cb_datamax_box(Fl_Value_Input*, void*) {
  mtxd.datamax = datamax_box->value();
load_mtx_cut();
}

Fl_Value_Input *datamin_box=(Fl_Value_Input *)0;

static void cb_datamin_box(Fl_Value_Input*, void*) {
  mtxd.datamin = datamin_box->value();
load_mtx_cut();
}

Fl_Light_Button *mtx_adjust=(Fl_Light_Button *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = controls = new Fl_Double_Window(315, 225, "controls");
    w = o;
    pattern_box = new Fl_Output(100, 35, 210, 25, "File Pattern:");
    { Fl_Value_Output* o = xstartbox = new Fl_Value_Output(135, 65, 55, 25, "X start, inc, end:");
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = xincbox = new Fl_Value_Output(195, 65, 55, 25);
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = xendbox = new Fl_Value_Output(255, 65, 55, 25);
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = ystartbox = new Fl_Value_Output(135, 95, 55, 25, "Y start, inc, end:");
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = yincbox = new Fl_Value_Output(195, 95, 55, 25);
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = yendbox = new Fl_Value_Output(255, 95, 55, 25);
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = x_box = new Fl_Value_Output(205, 135, 50, 25, "Current Position (x,y):");
      o->color(FL_BACKGROUND2_COLOR);
    }
    { Fl_Value_Output* o = y_box = new Fl_Value_Output(260, 135, 50, 25);
      o->color(FL_BACKGROUND2_COLOR);
    }
    filename_box = new Fl_Output(100, 195, 210, 25, "Current File:");
    { Fl_Choice* o = cmapch = new Fl_Choice(100, 5, 210, 25, "Colormap:");
      o->down_box(FL_BORDER_BOX);
      o->callback((Fl_Callback*)cmapch_cb);
    }
    output_counter = new Fl_Value_Input(205, 165, 100, 25, "Output Counter:");
    o->end();
    o->resizable(o);
  }
  { ImageWindow* o = iw = new ImageWindow(100, 100);
    w = o;
    o->box(FL_FLAT_BOX);
    o->color(FL_BACKGROUND_COLOR);
    o->selection_color(FL_BACKGROUND_COLOR);
    o->labeltype(FL_NO_LABEL);
    o->labelfont(0);
    o->labelsize(14);
    o->labelcolor(FL_FOREGROUND_COLOR);
    o->align(FL_ALIGN_TOP);
    o->when(FL_WHEN_RELEASE);
    o->end();
  }
  { Fl_Double_Window* o = xsecwin = new Fl_Double_Window(225, 180, "3D Cross Section Control");
    w = o;
    { Fl_Choice* o = dim = new Fl_Choice(95, 5, 125, 25, "Dimension:");
      o->down_box(FL_BORDER_BOX);
      o->callback((Fl_Callback*)cb_dim);
    }
    { Fl_Value_Input* o = indexbox = new Fl_Value_Input(60, 35, 35, 25, "Index:");
      o->callback((Fl_Callback*)cb_indexbox);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Slider* o = indexslider = new Fl_Slider(95, 35, 125, 25);
      o->type(3);
      o->step(1);
      o->callback((Fl_Callback*)cb_indexslider);
    }
    { Fl_Roller* o = indexroller = new Fl_Roller(60, 60, 160, 20);
      o->type(1);
      o->step(0.25);
      o->callback((Fl_Callback*)cb_indexroller);
    }
    { Fl_Button* o = new Fl_Button(135, 150, 85, 25, "dismiss");
      o->callback((Fl_Callback*)cb_dismiss);
    }
    { Fl_Value_Input* o = datamax_box = new Fl_Value_Input(70, 85, 150, 25, "datamax");
      o->callback((Fl_Callback*)cb_datamax_box);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Value_Input* o = datamin_box = new Fl_Value_Input(70, 115, 150, 25, "datamin");
      o->callback((Fl_Callback*)cb_datamin_box);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Light_Button* o = mtx_adjust = new Fl_Light_Button(5, 150, 125, 25, "Adjust on load");
      o->value(1);
    }
    o->end();
  }
  return w;
}
