// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef spynavigate_ui_h
#define spynavigate_ui_h
#include <FL/Fl.H>
#include "ImageWindow.H"
#include "spynavigate.H"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *controls;
#include <FL/Fl_Output.H>
extern Fl_Output *pattern_box;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *xstartbox;
extern Fl_Value_Output *xincbox;
extern Fl_Value_Output *xendbox;
extern Fl_Value_Output *ystartbox;
extern Fl_Value_Output *yincbox;
extern Fl_Value_Output *yendbox;
extern Fl_Value_Output *x_box;
extern Fl_Value_Output *y_box;
extern Fl_Output *filename_box;
#include <FL/Fl_Choice.H>
extern void cmapch_cb(Fl_Choice*, void*);
extern Fl_Choice *cmapch;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *output_counter;
extern ImageWindow *iw;
extern Fl_Double_Window *xsecwin;
extern Fl_Choice *dim;
extern Fl_Value_Input *indexbox;
#include <FL/Fl_Slider.H>
extern Fl_Slider *indexslider;
#include <FL/Fl_Roller.H>
extern Fl_Roller *indexroller;
#include <FL/Fl_Button.H>
extern Fl_Value_Input *datamax_box;
extern Fl_Value_Input *datamin_box;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *mtx_adjust;
Fl_Double_Window* make_window();
#endif
