.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SPYVIEW SECTION "May  6, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dat2pgm
.SH SYNOPSIS
.B dat2pgm [-l] [-h] [-p value (50)] < infile.dat > outfile.pgm
.br
.SH DESCRIPTION
.PP
A command line utility that converts an ascii data file into a pgm image.
.PP
As input, it will read a whitespace separated matrix of floats. The
program will determine the extrema of the data, and then map the data
onto 50% of the output image dynamic range, centered at half of the
output maxval of 65535. The output is then written as a 16 bit pgm
file that includes comment fields that are read by spyview that
specify the mapping of the grey value on the the floating point data
values in the input file.
.PP
The program can also produce and output image that is given by the
(base 10) log of the absolute value of input data, by specifying the
-l command line option.
.PP
The default percentage of the output dynamic range used is 50%, in
order to allow maximum flexibility in saturating the colormap in
spyview. The percentage of the output dynamic range to use can be
specified using the -p option.
.PP
The -h option shows a breif usage message.
.PP
.SH SEE ALSO
.BR spyview3d (1),
.BR spyview (1),
.BR spybrowse (1)
.br
.SH AUTHOR
This manual page was written by Gary Steele <gsteele@electron.mit.edu>,
for the Debian project (but may be used by others).





