.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SPYVIEW SECTION "May 19, 2005"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
splitfield
.SH SYNOPSIS
.B splitfield COLUMN < infile.dat > outfile.pgm
.br
.SH DESCRIPTION
.PP
A command line utility that inserts a blank line each time a column changes
value.  This is useful for gnuplot's pm3d mode and pm3d2dat.
.PP
As input, it will read a whitespace delimited table.  The program will
locate lines where COLUMN "column" changes, and insert an extra blank
line in it's output.
.PP
.SH SEE ALSO
.BR spyview3d (1),
.BR spyview (1),
.BR spybrowse (1),
.BR dat2pgm (1),
.BR gnuplot (1),
.BR pm3d2dat (1)
.br
.SH AUTHOR
This manual page was written by Oliver Dial <dial@mit.edu>
for the Debian project (but may be used by others).





