// Design size: 615x385
// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef cclass_chooser_h
#define cclass_chooser_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "colorbox.H"
#include <FL/Fl_Choice.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Box.H>

class CClass_Chooser : public Fl_Group {
public:
  CClass_Chooser(int xp=10, int yp=10, int wp=618, int hp=385, const char *namep="") ;
  Fl_Group *g;
  ColorBox *carea;
private:
  void cb_carea_i(ColorBox*, void*);
  static void cb_carea(ColorBox*, void*);
public:
  Fl_Choice *cspace;
  static Fl_Menu_Item menu_cspace[];
private:
  void cb_CIELuv_i(Fl_Menu_*, void*);
  static void cb_CIELuv(Fl_Menu_*, void*);
  void cb_CIELAB_i(Fl_Menu_*, void*);
  static void cb_CIELAB(Fl_Menu_*, void*);
  void cb_CIEXYZ_i(Fl_Menu_*, void*);
  static void cb_CIEXYZ(Fl_Menu_*, void*);
  void cb_CIExyY_i(Fl_Menu_*, void*);
  static void cb_CIExyY(Fl_Menu_*, void*);
  void cb_sRGB_i(Fl_Menu_*, void*);
  static void cb_sRGB(Fl_Menu_*, void*);
  void cb_Overscan_i(Fl_Value_Slider*, void*);
  static void cb_Overscan(Fl_Value_Slider*, void*);
public:
  Fl_Input *cOutput;
private:
  void cb_cOutput_i(Fl_Input*, void*);
  static void cb_cOutput(Fl_Input*, void*);
public:
  Fl_Input *sRGBOutput;
private:
  void cb_sRGBOutput_i(Fl_Input*, void*);
  static void cb_sRGBOutput(Fl_Input*, void*);
public:
  Fl_Input *HTMLOutput;
private:
  void cb_HTMLOutput_i(Fl_Input*, void*);
  static void cb_HTMLOutput(Fl_Input*, void*);
public:
  Fl_Output *sRGBGamut;
  Fl_Output *csGamut;
  Fl_Box *swatch;
  ccolor getcolor();
};

class CClass_Chooser_Window : public Fl_Double_Window {
public:
  CClass_Chooser_Window(int xp, int yp, int wp, int hp, const char *namep=0) ;
  CClass_Chooser *c;
};
#endif
