// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "PeakFinder_Control.h"
#include "ImageWindow.H"
#include "PeakFinder.H"
#include <FL/Fl_File_Chooser.H>

void PeakFinder_Control::cb_Save_i(Fl_Button*, void*) {
  iw->pf->save_peaks();
}
void PeakFinder_Control::cb_Save(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

void PeakFinder_Control::cb_dismiss_i(Fl_Button*, void*) {
  win->hide();
}
void PeakFinder_Control::cb_dismiss(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_dismiss_i(o,v);
}

void PeakFinder_Control::cb_thresh_i(Fl_Value_Input*, void*) {
  iw->pf->threashold = thresh->value();
slider->value(thresh->value());
iw->pf->calculate();
iw->damage(FL_DAMAGE_OVERLAY);
iw->redraw_overlay();
iw->plotLineCut();
}
void PeakFinder_Control::cb_thresh(Fl_Value_Input* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_thresh_i(o,v);
}

void PeakFinder_Control::cb_plot_peaks_i(Fl_Light_Button*, void*) {
  iw->damage(FL_DAMAGE_OVERLAY);
iw->redraw_overlay();
iw->plotLineCut();
}
void PeakFinder_Control::cb_plot_peaks(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_plot_peaks_i(o,v);
}

void PeakFinder_Control::cb_Help_i(Fl_Button*, void*) {
  if (helpwin->shown())
	helpwin->hide();
else
	helpwin->show();
}
void PeakFinder_Control::cb_Help(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_Help_i(o,v);
}

void PeakFinder_Control::cb_plot_valleys_i(Fl_Light_Button*, void*) {
  iw->damage(FL_DAMAGE_OVERLAY);
iw->redraw_overlay();
iw->plotLineCut();
}
void PeakFinder_Control::cb_plot_valleys(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_plot_valleys_i(o,v);
}

void PeakFinder_Control::cb_slider_i(Fl_Roller*, void*) {
  thresh->value(slider->value());
thresh->do_callback();
}
void PeakFinder_Control::cb_slider(Fl_Roller* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_slider_i(o,v);
}

void PeakFinder_Control::cb_slider_step_i(Fl_Value_Input*, void*) {
  slider->step(slider_step->value());
}
void PeakFinder_Control::cb_slider_step(Fl_Value_Input* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_slider_step_i(o,v);
}

void PeakFinder_Control::cb_recalc_i(Fl_Light_Button*, void*) {
  iw->pf->recalculate=recalc->value();
thresh->do_callback();
}
void PeakFinder_Control::cb_recalc(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_recalc_i(o,v);
}

void PeakFinder_Control::cb_vmax_enable_i(Fl_Light_Button*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_vmax_enable(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_vmax_enable_i(o,v);
}

void PeakFinder_Control::cb_valley_max_i(Fl_Value_Input*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_valley_max(Fl_Value_Input* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_valley_max_i(o,v);
}

void PeakFinder_Control::cb_pmin_enable_i(Fl_Light_Button*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_pmin_enable(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_pmin_enable_i(o,v);
}

void PeakFinder_Control::cb_do_outliers_i(Fl_Light_Button*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_do_outliers(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_do_outliers_i(o,v);
}

void PeakFinder_Control::cb_outlier_x_i(Fl_Spinner*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_outlier_x(Fl_Spinner* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_outlier_x_i(o,v);
}

void PeakFinder_Control::cb_outlier_y_i(Fl_Spinner*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_outlier_y(Fl_Spinner* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_outlier_y_i(o,v);
}

void PeakFinder_Control::cb_outlier_num_i(Fl_Spinner*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_outlier_num(Fl_Spinner* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_outlier_num_i(o,v);
}

void PeakFinder_Control::cb_peak_min_i(Fl_Value_Input*, void*) {
  thresh->do_callback();
}
void PeakFinder_Control::cb_peak_min(Fl_Value_Input* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_peak_min_i(o,v);
}

void PeakFinder_Control::cb_Toggle_i(Fl_Button*, void*) {
  static int peaks_on = 0;
static int valleys_on = 0;

if (hide_data->value())
{
	//Data is hidden: we should show the data and turn off any peaks
	peaks_on = plot_peaks->value();
	valleys_on = plot_valleys->value();
	plot_peaks->value(0);
	plot_valleys->value(0);
	hide_data->value(0);
}	
else
{
	// Data is shown: turn off the data
	// and if there are some internally saved peak settings
	// that are currently turned off, then we should restore them.
	if (!plot_peaks->value() && peaks_on)
		plot_peaks->value(1);
	if (!plot_valleys->value() && valleys_on)
		plot_valleys->value(1);
	hide_data->value(1);
}

hide_data->do_callback();
}
void PeakFinder_Control::cb_Toggle(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_Toggle_i(o,v);
}

void PeakFinder_Control::cb_hide_data_i(Fl_Light_Button*, void*) {
  iw->damage(FL_DAMAGE_OVERLAY);
iw->redraw_overlay();
}
void PeakFinder_Control::cb_hide_data(Fl_Light_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_hide_data_i(o,v);
}

void PeakFinder_Control::cb_peak_color_box_i(Fl_Button*, void*) {
  if (colorwin->shown())
	colorwin->hide();
else
	colorwin->show();
}
void PeakFinder_Control::cb_peak_color_box(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_peak_color_box_i(o,v);
}

void PeakFinder_Control::cb_valley_color_box_i(Fl_Button*, void*) {
  if (colorwin->shown())
	colorwin->hide();
else
	colorwin->show();
}
void PeakFinder_Control::cb_valley_color_box(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_valley_color_box_i(o,v);
}

void PeakFinder_Control::cb_Dismiss_i(Fl_Button*, void*) {
  helpwin->hide();
}
void PeakFinder_Control::cb_Dismiss(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_Dismiss_i(o,v);
}

void PeakFinder_Control::cb_peak_color_i(Fl_Color_Chooser* o, void*) {
  uchar r,g,b;
r = o->r()*255;
g = o->g()*255;
b = o->b()*255;
peak_color_box->color(fl_rgb_color(r,g,b));
peak_color_box->redraw();
iw->damage(FL_DAMAGE_OVERLAY);
iw->redraw_overlay();
}
void PeakFinder_Control::cb_peak_color(Fl_Color_Chooser* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_peak_color_i(o,v);
}

void PeakFinder_Control::cb_valley_color_i(Fl_Color_Chooser* o, void*) {
  valley_color_box->color(fl_rgb_color(o->r()*255, o->g()*255, o->b()*255));
valley_color_box->redraw();
iw->damage(FL_DAMAGE_OVERLAY);
iw->redraw_overlay();
}
void PeakFinder_Control::cb_valley_color(Fl_Color_Chooser* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_valley_color_i(o,v);
}

void PeakFinder_Control::cb_dismiss1_i(Fl_Button*, void*) {
  colorwin->hide();
}
void PeakFinder_Control::cb_dismiss1(Fl_Button* o, void* v) {
  ((PeakFinder_Control*)(o->parent()->user_data()))->cb_dismiss1_i(o,v);
}

PeakFinder_Control::PeakFinder_Control(ImageWindow *p_iw) {
  Fl_Double_Window* w;
  iw=p_iw;
  { Fl_Double_Window* o = win = new Fl_Double_Window(300, 185, "PeakFinder");
    w = o;
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(205, 110, 90, 20, "Save peaks");
      o->tooltip("Save peaks to \"basename.peaks\"");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_Save);
    }
    { Fl_Button* o = new Fl_Button(160, 160, 135, 20, "dismiss");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_dismiss);
    }
    { Fl_Value_Input* o = thresh = new Fl_Value_Input(75, 10, 220, 20, "Threshold:");
      o->labelsize(12);
      o->maximum(1e+06);
      o->value(0.5);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_thresh);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Light_Button* o = plot_peaks = new Fl_Light_Button(5, 85, 85, 20, "Plot Peaks");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_plot_peaks);
    }
    { Fl_Button* o = new Fl_Button(215, 135, 80, 20, "Help");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_Help);
    }
    { Fl_Light_Button* o = plot_valleys = new Fl_Light_Button(5, 110, 85, 20, "Plot Valleys");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_plot_valleys);
    }
    { Fl_Roller* o = slider = new Fl_Roller(120, 35, 175, 20);
      o->type(1);
      o->maximum(1e+06);
      o->step(0.01);
      o->value(0.5);
      o->callback((Fl_Callback*)cb_slider);
    }
    { Fl_Value_Input* o = slider_step = new Fl_Value_Input(55, 35, 65, 20, "step size");
      o->labelsize(10);
      o->value(0.01);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_slider_step);
    }
    { Fl_Light_Button* o = recalc = new Fl_Light_Button(205, 85, 90, 20, "Recalculate");
      o->tooltip("Recalculate peak positions during load and after image processing");
      o->value(1);
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_recalc);
    }
    { Fl_Light_Button* o = vmax_enable = new Fl_Light_Button(5, 60, 85, 20, "Valley max:");
      o->tooltip("Set a maximum data value for an identified valley");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_vmax_enable);
    }
    { Fl_Value_Input* o = valley_max = new Fl_Value_Input(95, 60, 50, 20);
      o->value(10);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_valley_max);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Light_Button* o = pmin_enable = new Fl_Light_Button(155, 60, 85, 20, "Peak min:");
      o->tooltip("Set a minium data value for an identified valley");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_pmin_enable);
    }
    { Fl_Light_Button* o = do_outliers = new Fl_Light_Button(5, 135, 125, 20, "Outlier Detection:");
      o->tooltip("Remove outliers (isolated peaks)");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_do_outliers);
    }
    { Fl_Spinner* o = outlier_x = new Fl_Spinner(25, 160, 55, 20, "X ");
      o->tooltip("Width of box for outlier rejection (pixels)");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_outlier_x);
    }
    { Fl_Spinner* o = outlier_y = new Fl_Spinner(95, 160, 55, 20, "Y");
      o->tooltip("Height of box for outlier rejection (pixels)");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_outlier_y);
    }
    { Fl_Spinner* o = outlier_num = new Fl_Spinner(150, 135, 55, 20, "n ");
      o->tooltip("Number of other peaks in window needed for peak not to be an outlier");
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_outlier_num);
    }
    { Fl_Value_Input* o = peak_min = new Fl_Value_Input(245, 60, 50, 20);
      o->value(10);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_peak_min);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Button* o = new Fl_Button(120, 110, 80, 20, "Toggle Data");
      o->tooltip("Save peaks to \"basename.peaks\"");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_Toggle);
    }
    { Fl_Light_Button* o = hide_data = new Fl_Light_Button(120, 85, 80, 20, "Hide Data");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_hide_data);
    }
    { Fl_Button* o = peak_color_box = new Fl_Button(95, 85, 20, 20);
      o->callback((Fl_Callback*)cb_peak_color_box);
    }
    { Fl_Button* o = valley_color_box = new Fl_Button(95, 110, 20, 20);
      o->callback((Fl_Callback*)cb_valley_color_box);
    }
    o->end();
  }
  { Fl_Double_Window* o = helpwin = new Fl_Double_Window(410, 355, "PeakFinder Help");
    w = o;
    o->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(5, 330, 400, 20, "Dismiss");
      o->callback((Fl_Callback*)cb_Dismiss);
    }
    { Fl_Input* o = helptext = new Fl_Input(5, 5, 400, 320);
      o->type(4);
      o->textsize(11);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  { Fl_Double_Window* o = colorwin = new Fl_Double_Window(210, 260, "Peak & Valley Colors");
    w = o;
    o->user_data((void*)(this));
    { Fl_Color_Chooser* o = peak_color = new Fl_Color_Chooser(5, 20, 200, 95, "Peaks");
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)cb_peak_color);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      o->rgb(0,1,0);
      o->end();
    }
    { Fl_Color_Chooser* o = valley_color = new Fl_Color_Chooser(5, 135, 200, 95, "Valleys");
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)cb_valley_color);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      o->rgb(1,1,0);
      o->end();
    }
    { Fl_Button* o = new Fl_Button(5, 235, 200, 20, "dismiss");
      o->labelsize(11);
      o->callback((Fl_Callback*)cb_dismiss1);
    }
    o->end();
  }
}
