#!/usr/bin/gawk -f
# Add ARGV[2] to the comments in a pgm file.
BEGIN {
  b=1;
  comments=ARGV[2];
  ARGV[2]="";
}

/^P./ {
  print;
  if(b == 1 ) {
    b = 0;
    print comments;
  }
  next;
}

{
print;
}


