// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "spybrowse_ui.h"

Fl_Double_Window *win=(Fl_Double_Window *)0;

Fl_Output *directory=(Fl_Output *)0;

static void cb_Browse(Fl_Button*, void*) {
  char *p = fl_dir_chooser("Choose new directory", "");
if (p != NULL) 
	directory->value(p);
chdir(p);
refreshb->do_callback();
}

Fl_Listbox *fb=(Fl_Listbox *)0;

Fl_Input *patternbox=(Fl_Input *)0;

Fl_Button *viewb=(Fl_Button *)0;

Fl_Button *view2b=(Fl_Button *)0;

Fl_Button *refreshb=(Fl_Button *)0;

Fl_Button *exitb=(Fl_Button *)0;

static void cb_exitb(Fl_Button*, void*) {
  while( Fl::first_window() ) Fl::first_window()->hide();
}

Fl_Light_Button *mtx=(Fl_Light_Button *)0;

static void cb_mtx(Fl_Light_Button*, void*) {
  update_pattern();
}

Fl_Light_Button *pgm=(Fl_Light_Button *)0;

static void cb_pgm(Fl_Light_Button*, void*) {
  update_pattern();
}

Fl_Light_Button *dat=(Fl_Light_Button *)0;

static void cb_dat(Fl_Light_Button*, void*) {
  update_pattern();
}

Fl_Light_Button *other=(Fl_Light_Button *)0;

static void cb_other(Fl_Light_Button*, void*) {
  update_pattern();
}

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = win = new Fl_Double_Window(340, 520, "SpyBrowse");
    w = o;
    { Fl_Group* o = new Fl_Group(0, 5, 335, 25);
      { Fl_Output* o = directory = new Fl_Output(80, 10, 180, 20, "Directory:");
        o->color(FL_BACKGROUND_COLOR);
        Fl_Group::current()->resizable(o);
      }
      { Fl_Button* o = new Fl_Button(260, 10, 75, 20, "Browse...");
        o->callback((Fl_Callback*)cb_Browse);
      }
      o->end();
    }
    { Fl_Listbox* o = fb = new Fl_Listbox(5, 35, 330, 405);
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)fb_cb);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      o->end();
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = new Fl_Group(65, 445, 270, 70);
      { Fl_Input* o = patternbox = new Fl_Input(65, 445, 270, 20, "pattern:");
        o->callback((Fl_Callback*)refreshb_cb);
        o->when(FL_WHEN_ENTER_KEY);
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    { Fl_Button* o = viewb = new Fl_Button(5, 495, 75, 20, "view");
      o->tooltip("Open all selected files in a single spyview window (Shortcut \"v\")");
      o->shortcut(0x76);
      o->callback((Fl_Callback*)viewb_cb);
    }
    { Fl_Button* o = view2b = new Fl_Button(85, 495, 95, 20, "view each");
      o->tooltip("Open all selected files in their own spyview window (Shortcut \"Ctrl-V\")");
      o->shortcut(0x40076);
      o->callback((Fl_Callback*)view2b_cb);
    }
    { Fl_Button* o = refreshb = new Fl_Button(185, 495, 85, 20, "Refresh");
      o->callback((Fl_Callback*)refreshb_cb);
    }
    { Fl_Button* o = exitb = new Fl_Button(275, 495, 60, 20, "exit");
      o->shortcut(0x80071);
      o->callback((Fl_Callback*)cb_exitb);
    }
    { Fl_Light_Button* o = mtx = new Fl_Light_Button(85, 470, 80, 20, "MTX");
      o->callback((Fl_Callback*)cb_mtx);
    }
    { Fl_Light_Button* o = pgm = new Fl_Light_Button(170, 470, 75, 20, "PGM");
      o->callback((Fl_Callback*)cb_pgm);
    }
    { Fl_Light_Button* o = dat = new Fl_Light_Button(5, 470, 75, 20, "DAT");
      o->callback((Fl_Callback*)cb_dat);
    }
    { Fl_Light_Button* o = other = new Fl_Light_Button(250, 470, 85, 20, "Other");
      o->callback((Fl_Callback*)cb_other);
    }
    o->end();
  }
  return w;
}
