// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "spypal_wizard.h"
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Help_Dialog.H>
extern std::string userdir;

void spypal_wizard_base::cb_steps_i(Fl_Input* o, void*) {
  if(atoi(o->value()) <= 0)
  o->value("8");
do_update();
}
void spypal_wizard_base::cb_steps(Fl_Input* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_steps_i(o,v);
}

void spypal_wizard_base::cb_Open_i(Fl_Menu_*, void*) {
  char *fname = fl_file_chooser("Load Colormap","Spypal Palette (*.spp)",(userdir+DIRECTORY_SEPARATOR+"cmaps").c_str());
if(fname != NULL)
  load(fname);
}
void spypal_wizard_base::cb_Open(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

void spypal_wizard_base::cb_Save_i(Fl_Menu_*, void*) {
  char *fname = fl_file_chooser("Save Colormap","Spypal Palette (*.spp)",(userdir+DIRECTORY_SEPARATOR+"cmaps"+DIRECTORY_SEPARATOR+"user").c_str());
if(fname != NULL)
  save(fname);
}
void spypal_wizard_base::cb_Save(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

void spypal_wizard_base::cb_Export_i(Fl_Menu_*, void*) {
  char *fname = fl_file_chooser("Export as Text","","");
if(fname)
  dump_colormap_text(fname);
}
void spypal_wizard_base::cb_Export(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Export_i(o,v);
}

void spypal_wizard_base::cb_Export1_i(Fl_Menu_*, void*) {
  char *fname = fl_file_chooser("Export as Image","","");
if(fname)
  dump_colormap_ppm(fname);
}
void spypal_wizard_base::cb_Export1(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Export1_i(o,v);
}

void spypal_wizard_base::cb_Quit_i(Fl_Menu_*, void*) {
  exit(0);
}
void spypal_wizard_base::cb_Quit(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

void spypal_wizard_base::cb_Manual_i(Fl_Menu_*, void*) {
  static Fl_Help_Dialog hv;
std::string file;
file = spypal_sharedir + DIRECTORY_SEPARATOR + "html" + DIRECTORY_SEPARATOR + "spypal_help.html";
hv.load(file.c_str());
hv.show();
}
void spypal_wizard_base::cb_Manual(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Manual_i(o,v);
}

Fl_Menu_Item spypal_wizard_base::menu_[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open", 0,  (Fl_Callback*)spypal_wizard_base::cb_Open, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Save", 0,  (Fl_Callback*)spypal_wizard_base::cb_Save, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Export &Text", 0,  (Fl_Callback*)spypal_wizard_base::cb_Export, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Export &Image", 0,  (Fl_Callback*)spypal_wizard_base::cb_Export1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Quit", 0,  (Fl_Callback*)spypal_wizard_base::cb_Quit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Manual", 0,  (Fl_Callback*)spypal_wizard_base::cb_Manual, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

void spypal_wizard_base::cb_Space_i(Fl_Button*, void*) {
  space_evenly();
}
void spypal_wizard_base::cb_Space(Fl_Button* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_Space_i(o,v);
}

void spypal_wizard_base::cb_colorspace_i(Fl_Choice*, void*) {
  do_update();
}
void spypal_wizard_base::cb_colorspace(Fl_Choice* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_colorspace_i(o,v);
}

Fl_Menu_Item spypal_wizard_base::menu_colorspace[] = {
 {"LAB", 0,  0, (void*)(&cc_CIELAB), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"sRGB", 0,  0, (void*)(&cc_sRGB), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"HSV", 0,  0, (void*)(&cc_HSV), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CIECAM02", 0,  0, (void*)(&cc_CIECAM02), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Luv", 0,  0, (void*)(&cc_CIELuv), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"XYZ", 0,  0, (void*)(&cc_CIEXYZ), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void spypal_wizard_base::cb_metricspace_i(Fl_Choice*, void*) {
  do_update();
}
void spypal_wizard_base::cb_metricspace(Fl_Choice* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_metricspace_i(o,v);
}

Fl_Menu_Item spypal_wizard_base::menu_metricspace[] = {
 {"LAB", 0,  0, (void*)(&cc_CIELAB), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"sRGB", 0,  0, (void*)(&cc_sRGB), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"HSV", 0,  0, (void*)(&cc_HSV), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CIECAM02", 0,  0, (void*)(&cc_CIECAM02), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Luv", 0,  0, (void*)(&cc_CIELuv), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"XYZ", 0,  0, (void*)(&cc_CIEXYZ), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void spypal_wizard_base::cb_opt_direction_i(Fl_Choice*, void*) {
  do_update();
}
void spypal_wizard_base::cb_opt_direction(Fl_Choice* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_opt_direction_i(o,v);
}

Fl_Menu_Item spypal_wizard_base::menu_opt_direction[] = {
 {"Straight", 0,  0, (void*)(OPTS_STRAIGHT), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CCW", 0,  0, (void*)(OPTS_CCW), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CW", 0,  0, (void*)(OPTS_CW), 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void spypal_wizard_base::cb_grad_style_i(Fl_Choice* o, void*) {
  if(o->mvalue())
  o->mvalue()->do_callback(o);
}
void spypal_wizard_base::cb_grad_style(Fl_Choice* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_grad_style_i(o,v);
}

void spypal_wizard_base::cb_Luv_i(Fl_Menu_*, void*) {
  colorspace->value(colorspace->find_item("Luv"));
metricspace->value(metricspace->find_item("Luv"));
opt_direction->value(opt_direction->find_item("Straight"));
do_update();
}
void spypal_wizard_base::cb_Luv(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_Luv_i(o,v);
}

void spypal_wizard_base::cb_sRGB_i(Fl_Menu_*, void*) {
  colorspace->value(colorspace->find_item("sRGB"));
metricspace->value(metricspace->find_item("sRGB"));
opt_direction->value(opt_direction->find_item("Straight"));
do_update();
}
void spypal_wizard_base::cb_sRGB(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_sRGB_i(o,v);
}

void spypal_wizard_base::cb_HSV_i(Fl_Menu_*, void*) {
  colorspace->value(colorspace->find_item("HSV"));
metricspace->value(metricspace->find_item("Luv"));
opt_direction->value(opt_direction->find_item("Straight"));
do_update();
}
void spypal_wizard_base::cb_HSV(Fl_Menu_* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_HSV_i(o,v);
}

Fl_Menu_Item spypal_wizard_base::menu_grad_style[] = {
 {"Luv", 0,  (Fl_Callback*)spypal_wizard_base::cb_Luv, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"sRGB", 0,  (Fl_Callback*)spypal_wizard_base::cb_sRGB, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"HSV (perceptual ramps)", 0,  (Fl_Callback*)spypal_wizard_base::cb_HSV, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void spypal_wizard_base::cb_advanced_i(Fl_Light_Button* o, void*) {
  if(o->value())
  { basic_controls->hide();
    advanced_controls->show();
  }
else
  { basic_controls->show();
    advanced_controls->hide();
    grad_style->do_callback();
  };
}
void spypal_wizard_base::cb_advanced(Fl_Light_Button* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->user_data()))->cb_advanced_i(o,v);
}

void spypal_wizard_base::cb_waypoints_i(Fl_Spinner*, void*) {
  import_update();
}
void spypal_wizard_base::cb_waypoints(Fl_Spinner* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_waypoints_i(o,v);
}

void spypal_wizard_base::cb_Residuals_i(Fl_Button*, void*) {
  import_residuals();
}
void spypal_wizard_base::cb_Residuals(Fl_Button* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_Residuals_i(o,v);
}

void spypal_wizard_base::cb_Dismiss_i(Fl_Button*, void*) {
  import_controls->hide();
}
void spypal_wizard_base::cb_Dismiss(Fl_Button* o, void* v) {
  ((spypal_wizard_base*)(o->parent()->parent()->user_data()))->cb_Dismiss_i(o,v);
}

spypal_wizard_base::spypal_wizard_base() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = win = new Fl_Double_Window(935, 490, "Spypal");
    w = o;
    o->user_data((void*)(this));
    { Fl_Input* o = steps = new Fl_Input(585, 0, 110, 25, "Steps");
      o->callback((Fl_Callback*)cb_steps);
      o->when(FL_WHEN_ENTER_KEY);
      o->value("512");
    }
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 95, 25);
      o->menu(menu_);
    }
    { Fl_Color_Chooser* o = cc = new Fl_Color_Chooser(0, 175, 425, 275);
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      o->selection_color(FL_BACKGROUND2_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      o->rgb(1.0,1.0,1.0);
    }
    { Fl_Spypal_Gradient* o = grad = new Fl_Spypal_Gradient(0, 50, 935, 125);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    { Fl_Scroll* o = swatches = new Fl_Scroll(425, 175, 510, 274);
      o->type(2);
      o->box(FL_DOWN_BOX);
      o->end();
    }
    { Fl_Output* o = tooltip = new Fl_Output(0, 450, 935, 45);
      o->type(12);
      o->textsize(12);
    }
    { Fl_Button* o = new Fl_Button(705, 0, 100, 25, "Space Evenly");
      o->callback((Fl_Callback*)cb_Space);
    }
    { Fl_Group* o = advanced_controls = new Fl_Group(95, 0, 445, 29);
      o->hide();
      { Fl_Choice* o = colorspace = new Fl_Choice(184, 1, 90, 25, "Colorspace");
        o->down_box(FL_BORDER_BOX);
        o->callback((Fl_Callback*)cb_colorspace);
        o->menu(menu_colorspace);
      }
      { Fl_Choice* o = metricspace = new Fl_Choice(330, 1, 90, 25, "Metric");
        o->down_box(FL_BORDER_BOX);
        o->callback((Fl_Callback*)cb_metricspace);
        o->when(FL_WHEN_RELEASE_ALWAYS);
        o->menu(menu_metricspace);
      }
      { Fl_Choice* o = opt_direction = new Fl_Choice(455, 1, 85, 24, "Path");
        o->down_box(FL_BORDER_BOX);
        o->callback((Fl_Callback*)cb_opt_direction);
        o->menu(menu_opt_direction);
      }
      o->end();
    }
    { Fl_Group* o = basic_controls = new Fl_Group(95, 0, 445, 25);
      { Fl_Choice* o = grad_style = new Fl_Choice(280, 0, 245, 25, "Gradient Style");
        o->down_box(FL_BORDER_BOX);
        o->callback((Fl_Callback*)cb_grad_style);
        o->menu(menu_grad_style);
      }
      o->end();
    }
    { Fl_Light_Button* o = advanced = new Fl_Light_Button(825, 0, 100, 25, "Advanced");
      o->callback((Fl_Callback*)cb_advanced);
    }
    { Fl_Group* o = import_controls = new Fl_Group(477, 25, 449, 25, "Import Controls");
      o->box(FL_DOWN_BOX);
      o->align(FL_ALIGN_LEFT);
      o->hide();
      { Fl_Spinner* o = waypoints = new Fl_Spinner(812, 28, 40, 20, "Waypoints");
        o->callback((Fl_Callback*)cb_waypoints);
      }
      { Fl_Output* o = import_error = new Fl_Output(522, 28, 130, 20, "Error");
        o->tooltip("Total error (worst single-point error), measured as cartesian distance in sRG\
B space.");
      }
      { Fl_Button* o = new Fl_Button(657, 28, 74, 20, "Residuals");
        o->callback((Fl_Callback*)cb_Residuals);
      }
      { Fl_Button* o = new Fl_Button(857, 28, 64, 20, "Dismiss");
        o->callback((Fl_Callback*)cb_Dismiss);
      }
      o->end();
    }
    o->end();
    o->resizable(o);
  }
}

void spypal_wizard_base::do_update() {
  if(import_controls->visible())
              {
                import_update(); 		
              }
            else
              { recalculate(true); grad->redraw();}
}

void spypal_wizard_base::recalculate(bool repos ) {
}

void spypal_wizard_base::save(std::string fname) {
}

void spypal_wizard_base::load(std::string fname) {
}

void spypal_wizard_base::space_evenly() {
}

void spypal_wizard_base::import_update() {
}

void spypal_wizard_base::import_residuals() {
}

void spypal_slider_editor::cb_position_i(Fl_Input* o, void*) {
  slider->loc = atof(o->value());
update_slider();
}
void spypal_slider_editor::cb_position(Fl_Input* o, void* v) {
  ((spypal_slider_editor*)(o->parent()->user_data()))->cb_position_i(o,v);
}

void spypal_slider_editor::cb_Dismiss1_i(Fl_Button*, void*) {
  win->hide();
}
void spypal_slider_editor::cb_Dismiss1(Fl_Button* o, void* v) {
  ((spypal_slider_editor*)(o->parent()->user_data()))->cb_Dismiss1_i(o,v);
}

void spypal_slider_editor::cb_locked_i(Fl_Check_Button* o, void*) {
  slider->locked = o->value();
update_slider();
}
void spypal_slider_editor::cb_locked(Fl_Check_Button* o, void* v) {
  ((spypal_slider_editor*)(o->parent()->user_data()))->cb_locked_i(o,v);
}

void spypal_slider_editor::update_slider() {
  slider->g->recalculate(true);
slider->g->redraw();
}

spypal_slider_editor::spypal_slider_editor() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = win = new Fl_Double_Window(160, 75, "Waypoint");
    w = o;
    o->user_data((void*)(this));
    { Fl_Input* o = position = new Fl_Input(10, 20, 145, 25, "Position (0.0-1.0)");
      o->type(1);
      o->callback((Fl_Callback*)cb_position);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = new Fl_Button(80, 50, 74, 25, "Dismiss");
      o->callback((Fl_Callback*)cb_Dismiss1);
    }
    { Fl_Check_Button* o = locked = new Fl_Check_Button(60, 55, 15, 15, "Locked");
      o->down_box(FL_DOWN_BOX);
      o->callback((Fl_Callback*)cb_locked);
      o->align(FL_ALIGN_LEFT);
    }
    o->end();
  }
}

Fl_Double_Window *spypal_text_window=(Fl_Double_Window *)0;

Fl_Text_Display *cmap_text_display=(Fl_Text_Display *)0;

Fl_Double_Window* make_spypal_text_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = spypal_text_window = new Fl_Double_Window(380, 375, "Spypal Colormap");
    w = o;
    { Fl_Text_Display* o = cmap_text_display = new Fl_Text_Display(0, 0, 380, 375);
      o->textfont(4);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  return w;
}
