// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef spyrotate_ui_h
#define spyrotate_ui_h
#include <FL/Fl.H>
#include "ImageWindow.H"
#include "spyrotate.h"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *controls;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *angle_value;
#include <FL/Fl_Roller.H>
extern Fl_Roller *angle_roller;
#include <FL/Fl_Button.H>
extern ImageWindow *iw1;
extern ImageWindow *iw2;
Fl_Double_Window* make_window();
#endif
