// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "spyview3d_ui.h"

Fl_Double_Window *control=(Fl_Double_Window *)0;

Fl_Choice *filech=(Fl_Choice *)0;

Fl_Choice *cmapch=(Fl_Choice *)0;

Fl_Light_Button *greybutton=(Fl_Light_Button *)0;

static void cb_greybutton(Fl_Light_Button*, void*) {
  iw3d->grey=greybutton->value();
iw3d->redraw();
}

Fl_Round_Button *pointsbutton=(Fl_Round_Button *)0;

static void cb_pointsbutton(Fl_Round_Button*, void*) {
  iw3d->surfacetype = POINTS;
iw3d->redraw();
}

Fl_Round_Button *linemeshbutton=(Fl_Round_Button *)0;

static void cb_linemeshbutton(Fl_Round_Button*, void*) {
  iw3d->surfacetype = LINEMESH;
iw3d->redraw();
}

Fl_Round_Button *polygonsbutton=(Fl_Round_Button *)0;

static void cb_polygonsbutton(Fl_Round_Button*, void*) {
  iw3d->surfacetype = POLYGONS;
iw3d->redraw();
}

Fl_Button *resetanglebutton=(Fl_Button *)0;

static void cb_resetanglebutton(Fl_Button*, void*) {
  iw3d->remove_trans("angle");
iw3d->redraw();
}

Fl_Button *resetzoombutton=(Fl_Button *)0;

static void cb_resetzoombutton(Fl_Button*, void*) {
  iw3d->remove_trans("scale");
iw3d->redraw();
}

Fl_Button *resettranslatebutton=(Fl_Button *)0;

static void cb_resettranslatebutton(Fl_Button*, void*) {
  iw3d->remove_trans("translate");
iw3d->redraw();
}

Fl_Button *resetallbutton=(Fl_Button *)0;

static void cb_resetallbutton(Fl_Button*, void*) {
  iw3d->remove_all_trans();
iw3d->redraw();
}

Fl_Value_Input *psival=(Fl_Value_Input *)0;

static void cb_psival(Fl_Value_Input* o, void*) {
  double val=((Fl_Valuator *)o)->value();
iw3d->setPsi(val);
}

Fl_Value_Input *thetaval=(Fl_Value_Input *)0;

static void cb_thetaval(Fl_Value_Input* o, void*) {
  double val=((Fl_Valuator *)o)->value();
iw3d->setTheta(val);
}

Fl_Value_Input *zoomval=(Fl_Value_Input *)0;

static void cb_zoomval(Fl_Value_Input* o, void*) {
  double val=((Fl_Valuator *)o)->value();
iw3d->setScaleZ(val*iw3d->getScaleZ()/iw3d->getScaleX());
iw3d->setScaleX(val);
iw3d->setScaleY(val);
}

Fl_Value_Input *zscaleval=(Fl_Value_Input *)0;

static void cb_zscaleval(Fl_Value_Input* o, void*) {
  double val=((Fl_Valuator *)o)->value();
iw3d->setScaleZ(val);
}

Fl_Value_Input *xtranval=(Fl_Value_Input *)0;

static void cb_xtranval(Fl_Value_Input* o, void*) {
  double val=((Fl_Valuator *)o)->value();
iw3d->setTranslateX(val);
}

Fl_Value_Input *ytranval=(Fl_Value_Input *)0;

static void cb_ytranval(Fl_Value_Input* o, void*) {
  double val=((Fl_Valuator *)o)->value();
iw3d->setTranslateY(val);
}

Fl_Light_Button *planeb=(Fl_Light_Button *)0;

static void cb_planeb(Fl_Light_Button*, void*) {
  iw3d->plane = planeb->value();
iw3d->redraw();
}

Fl_Button *fitplane=(Fl_Button *)0;

static void cb_fitplane(Fl_Button*, void*) {
  iw3d->fitPlane();
plane_b->value(iw3d->plane_b);
plane_broller->value(iw3d->plane_b);
plane_bslider->value(iw3d->plane_b);
plane_a->value(iw3d->plane_a);
plane_aroller->value(iw3d->plane_a);
plane_aslider->value(iw3d->plane_a);
iw3d->redraw();
}

Fl_Value_Input *plane_a=(Fl_Value_Input *)0;

static void cb_plane_a(Fl_Value_Input*, void*) {
  iw3d->plane_a = plane_a->value();
iw3d->redraw();
plane_aroller->value(plane_a->value());
plane_aslider->value(plane_a->value());
}

Fl_Slider *plane_aslider=(Fl_Slider *)0;

static void cb_plane_aslider(Fl_Slider* o, void*) {
  plane_a->value(((Fl_Valuator *) o)->value() );
plane_a->do_callback();
}

Fl_Roller *plane_aroller=(Fl_Roller *)0;

static void cb_plane_aroller(Fl_Roller* o, void*) {
  plane_a->value(((Fl_Valuator *) o)->value() );
plane_a->do_callback();
}

Fl_Value_Input *plane_b=(Fl_Value_Input *)0;

static void cb_plane_b(Fl_Value_Input*, void*) {
  iw3d->plane_b = plane_b->value();
iw3d->redraw();
plane_broller->value(plane_b->value());
plane_bslider->value(plane_b->value());
}

Fl_Slider *plane_bslider=(Fl_Slider *)0;

static void cb_plane_bslider(Fl_Slider* o, void*) {
  plane_b->value(((Fl_Valuator *) o)->value() );
plane_b->do_callback();
}

Fl_Roller *plane_broller=(Fl_Roller *)0;

static void cb_plane_broller(Fl_Roller* o, void*) {
  plane_b->value(((Fl_Valuator *) o)->value() );
plane_b->do_callback();
}

Fl_Input *savebox=(Fl_Input *)0;

Fl_Button *saveb=(Fl_Button *)0;

Fl_Round_Button *postscriptbutton=(Fl_Round_Button *)0;

Fl_Round_Button *epsbutton=(Fl_Round_Button *)0;

Fl_Round_Button *latexbutton=(Fl_Round_Button *)0;

Fl_Button *show_lighting_controls_window=(Fl_Button *)0;

static void cb_show_lighting_controls_window(Fl_Button*, void*) {
  if (lwin->shown())
 lwin->hide();
else
 lwin->show();
}

static void cb_Image(Fl_Button*, void*) {
  if (procwin->shown())
 procwin->hide();
else
 procwin->show();
}

static void cb_Colors(Fl_Button*, void*) {
  if (cmapwin->shown())
 cmapwin->hide();
else
 cmapwin->show();
}

static void cb_Exit(Fl_Button*, void*) {
  exit(0);
}

Fl_Button *dismissb=(Fl_Button *)0;

static void cb_dismissb(Fl_Button*, void*) {
  control->hide();
}

Fl_Double_Window *lwin=(Fl_Double_Window *)0;

static void cb_dismiss(Fl_Button*, void*) {
  lwin->hide();
}

Fl_Value_Slider *diffuseslider=(Fl_Value_Slider *)0;

static void cb_diffuseslider(Fl_Value_Slider*, void*) {
  iw3d->diffuse=diffuseslider->value();
iw3d->redraw();
}

Fl_Value_Slider *specularslider=(Fl_Value_Slider *)0;

static void cb_specularslider(Fl_Value_Slider*, void*) {
  iw3d->specular=specularslider->value();
iw3d->redraw();
}

Fl_Value_Slider *ambientslider=(Fl_Value_Slider *)0;

static void cb_ambientslider(Fl_Value_Slider*, void*) {
  iw3d->ambient=ambientslider->value();
iw3d->redraw();
}

Fl_Light_Button *plot_light_positions=(Fl_Light_Button *)0;

static void cb_plot_light_positions(Fl_Light_Button*, void*) {
  iw3d->plot_light_positions = plot_light_positions->value();
iw3d->redraw();
}

Fl_Light_Button *lightingbutton=(Fl_Light_Button *)0;

static void cb_lightingbutton(Fl_Light_Button*, void*) {
  iw3d->lighting=lightingbutton->value();
iw3d->redraw();
}

static void cb_Point(Fl_Round_Button*, void*) {
  iw3d->light_type = POINTSOURCE;
iw3d->redraw();
}

static void cb_Directional(Fl_Round_Button*, void*) {
  iw3d->light_type = DIRECTIONAL;
iw3d->redraw();
}

static void cb_reset(Fl_Button*, void*) {
  double vals[] = {.2, 1, 0, 0, 90, 1};
Fl_Valuator *widgets[] = {
	ambientslider,
	diffuseslider,
	specularslider,
	phiroll,
	thetaroll, 
	rroll};
for (int i=0; i<6; i++)
{
 (widgets[i])->value(vals[i]);
 (widgets[i])->do_callback();
};
}

Fl_Roller *phiroll=(Fl_Roller *)0;

static void cb_phiroll(Fl_Roller*, void*) {
  double val = phiroll->value();
val = fmod(val, 360);
iw3d->light_phi = val;
lphival->value(val);
iw3d->redraw();
}

Fl_Roller *thetaroll=(Fl_Roller *)0;

static void cb_thetaroll(Fl_Roller*, void*) {
  double val = thetaroll->value();
val = fmod(val, 360);
iw3d->light_theta = val;
lthetaval->value(val);
iw3d->redraw();
}

Fl_Roller *rroll=(Fl_Roller *)0;

static void cb_rroll(Fl_Roller*, void*) {
  iw3d->light_r = rroll->value();
rval->value(rroll->value());
iw3d->redraw();
}

Fl_Value_Output *lphival=(Fl_Value_Output *)0;

Fl_Value_Output *lthetaval=(Fl_Value_Output *)0;

Fl_Value_Output *rval=(Fl_Value_Output *)0;

Fl_Double_Window *imagewindow=(Fl_Double_Window *)0;

ImageWindow3d *iw3d=(ImageWindow3d *)0;

Fl_Double_Window *procwin=(Fl_Double_Window *)0;

Fl_Browser *options=(Fl_Browser *)0;

Fl_Browser *pqueue=(Fl_Browser *)0;

static void cb_add(Fl_Button*, void*) {
  int n = options->value();
if (n != 0)
  pqueue->add(options->text(n));
filech->do_callback();
}

static void cb_remove(Fl_Button*, void*) {
  int n = pqueue->value();
if (n != 0)
{
  pqueue->remove(n);
  filech->do_callback();
};
}

static void cb_clear(Fl_Button*, void*) {
  pqueue->clear();
filech->do_callback();
}

static void cb_up(Fl_Button*, void*) {
  int n = pqueue->value();
if (n > 1)
{
 pqueue->move(n,n-1);
 filech->do_callback();
};
}

static void cb_down(Fl_Button*, void*) {
  int n = pqueue->value();
if ((n > 0) && (n < pqueue->size()))
{
 pqueue->move(n,n+1);
 filech->do_callback();
};
}

static void cb_dismiss1(Fl_Button*, void*) {
  procwin->hide();
}

Fl_Double_Window *cmapwin=(Fl_Double_Window *)0;

Fl_Value_Slider *wslider=(Fl_Value_Slider *)0;

static void cb_wslider(Fl_Value_Slider*, void*) {
  iw3d->cmapwidth = wslider->value();
wroller->value(wslider->value());
iw3d->redraw();
}

Fl_Roller *wroller=(Fl_Roller *)0;

static void cb_wroller(Fl_Roller*, void*) {
  wslider->value(wroller->value());
wslider->do_callback();
}

Fl_Value_Slider *cslider=(Fl_Value_Slider *)0;

static void cb_cslider(Fl_Value_Slider*, void*) {
  iw3d->cmapoffset = cslider->value();
croller->value(cslider->value());
iw3d->redraw();
}

Fl_Roller *croller=(Fl_Roller *)0;

static void cb_croller(Fl_Roller*, void*) {
  cslider->value(croller->value());
cslider->do_callback();
}

static void cb_Invert(Fl_Light_Button* o, void*) {
  iw3d->invert = ((Fl_Button *)o)->value();
iw3d->redraw();
}

static void cb_Nomalize(Fl_Button*, void*) {
  iw3d->normalize();
wslider->value(1);
wslider->do_callback();
cslider->value(0);
cslider->do_callback();
iw3d->redraw();
}

static void cb_Negate(Fl_Light_Button* o, void*) {
  iw3d->negate = ((Fl_Button *)o)->value();
iw3d->redraw();
}

static void cb_dismiss2(Fl_Button*, void*) {
  cmapwin->hide();
}

void make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = control = new Fl_Double_Window(240, 585, "Controls");
    w = o;
    { Fl_Choice* o = filech = new Fl_Choice(45, 5, 190, 25, "file:");
      o->down_box(FL_BORDER_BOX);
      o->callback((Fl_Callback*)filech_cb);
    }
    { Fl_Choice* o = cmapch = new Fl_Choice(60, 35, 175, 25, "cmap:");
      o->down_box(FL_BORDER_BOX);
      o->callback((Fl_Callback*)cmapch_cb);
    }
    { Fl_Light_Button* o = greybutton = new Fl_Light_Button(185, 85, 50, 20, "Grey");
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_greybutton);
    }
    { Fl_Group* o = new Fl_Group(20, 80, 210, 25, "Surface Type");
      o->align(FL_ALIGN_TOP_LEFT);
      { Fl_Round_Button* o = pointsbutton = new Fl_Round_Button(20, 85, 25, 20, "Pnt");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_pointsbutton);
      }
      { Fl_Round_Button* o = linemeshbutton = new Fl_Round_Button(70, 85, 25, 20, "Line");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_linemeshbutton);
      }
      { Fl_Round_Button* o = polygonsbutton = new Fl_Round_Button(125, 85, 25, 20, "Poly");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->value(1);
        o->callback((Fl_Callback*)cb_polygonsbutton);
      }
      o->end();
    }
    { Fl_Button* o = resetanglebutton = new Fl_Button(5, 115, 115, 25, "Reset Angle");
      o->callback((Fl_Callback*)cb_resetanglebutton);
    }
    { Fl_Button* o = resetzoombutton = new Fl_Button(125, 115, 110, 25, "Reset Zoom");
      o->callback((Fl_Callback*)cb_resetzoombutton);
    }
    { Fl_Button* o = resettranslatebutton = new Fl_Button(5, 145, 115, 25, "Reset Trans.");
      o->callback((Fl_Callback*)cb_resettranslatebutton);
    }
    { Fl_Button* o = resetallbutton = new Fl_Button(125, 145, 110, 25, "Reset All");
      o->callback((Fl_Callback*)cb_resetallbutton);
    }
    { Fl_Value_Input* o = psival = new Fl_Value_Input(130, 185, 45, 25, "Psi, Theta:");
      o->callback((Fl_Callback*)cb_psival);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Value_Input* o = thetaval = new Fl_Value_Input(185, 185, 45, 25, ",");
      o->callback((Fl_Callback*)cb_thetaval);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Value_Input* o = zoomval = new Fl_Value_Input(130, 220, 45, 25, "Zoom, Zscale:");
      o->callback((Fl_Callback*)cb_zoomval);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Value_Input* o = zscaleval = new Fl_Value_Input(185, 220, 45, 25, ",");
      o->callback((Fl_Callback*)cb_zscaleval);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Value_Input* o = xtranval = new Fl_Value_Input(130, 255, 45, 25, "X,Y Translation:");
      o->callback((Fl_Callback*)cb_xtranval);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Value_Input* o = ytranval = new Fl_Value_Input(185, 255, 45, 25, ",");
      o->callback((Fl_Callback*)cb_ytranval);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Light_Button* o = planeb = new Fl_Light_Button(10, 295, 110, 25, "Sub Plane");
      o->callback((Fl_Callback*)cb_planeb);
    }
    { Fl_Button* o = fitplane = new Fl_Button(125, 295, 110, 25, "Fit Plane");
      o->callback((Fl_Callback*)cb_fitplane);
    }
    { Fl_Value_Input* o = plane_a = new Fl_Value_Input(45, 325, 70, 20, "Vert:");
      o->minimum(-2);
      o->maximum(2);
      o->step(0.0001);
      o->callback((Fl_Callback*)cb_plane_a);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Slider* o = plane_aslider = new Fl_Slider(115, 325, 120, 20);
      o->type(3);
      o->minimum(-2);
      o->maximum(2);
      o->callback((Fl_Callback*)cb_plane_aslider);
    }
    { Fl_Roller* o = plane_aroller = new Fl_Roller(45, 345, 190, 15);
      o->type(1);
      o->minimum(-2);
      o->maximum(2);
      o->step(0.001);
      o->callback((Fl_Callback*)cb_plane_aroller);
    }
    { Fl_Value_Input* o = plane_b = new Fl_Value_Input(45, 370, 70, 20, "Horz:");
      o->minimum(-2);
      o->maximum(2);
      o->step(0.0001);
      o->callback((Fl_Callback*)cb_plane_b);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Slider* o = plane_bslider = new Fl_Slider(115, 370, 120, 20);
      o->type(3);
      o->minimum(-2);
      o->maximum(2);
      o->callback((Fl_Callback*)cb_plane_bslider);
    }
    { Fl_Roller* o = plane_broller = new Fl_Roller(45, 390, 190, 15);
      o->type(1);
      o->minimum(-2);
      o->maximum(2);
      o->step(0.001);
      o->callback((Fl_Callback*)cb_plane_broller);
    }
    savebox = new Fl_Input(75, 420, 160, 25, "save as:");
    { Fl_Button* o = saveb = new Fl_Button(170, 450, 65, 25, "save");
      o->callback((Fl_Callback*)saveb_cb);
    }
    { Fl_Group* o = new Fl_Group(10, 470, 215, 50, "Saved file format:");
      o->align(FL_ALIGN_TOP_LEFT);
      { Fl_Round_Button* o = postscriptbutton = new Fl_Round_Button(10, 475, 25, 25, "PostScript");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->value(1);
      }
      { Fl_Round_Button* o = epsbutton = new Fl_Round_Button(10, 495, 25, 25, "EPS");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      { Fl_Round_Button* o = latexbutton = new Fl_Round_Button(105, 475, 25, 25, "LaTeX");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
      }
      o->end();
    }
    { Fl_Button* o = show_lighting_controls_window = new Fl_Button(5, 525, 75, 25, "Lighitng");
      o->callback((Fl_Callback*)cb_show_lighting_controls_window);
    }
    { Fl_Button* o = new Fl_Button(85, 525, 150, 25, "Image Processing");
      o->callback((Fl_Callback*)cb_Image);
    }
    { Fl_Button* o = new Fl_Button(5, 555, 65, 25, "Colors");
      o->callback((Fl_Callback*)cb_Colors);
    }
    { Fl_Button* o = new Fl_Button(75, 555, 75, 25, "Exit");
      o->callback((Fl_Callback*)cb_Exit);
    }
    { Fl_Button* o = dismissb = new Fl_Button(155, 555, 80, 25, "dismiss");
      o->callback((Fl_Callback*)cb_dismissb);
    }
    o->end();
  }
  { Fl_Double_Window* o = lwin = new Fl_Double_Window(230, 335, "Lighting Controls");
    w = o;
    { Fl_Button* o = new Fl_Button(120, 305, 105, 25, "dismiss");
      o->callback((Fl_Callback*)cb_dismiss);
    }
    { Fl_Value_Slider* o = diffuseslider = new Fl_Value_Slider(65, 145, 160, 25, "Diffuse");
      o->type(3);
      o->step(0.001);
      o->value(1);
      o->callback((Fl_Callback*)cb_diffuseslider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Value_Slider* o = specularslider = new Fl_Value_Slider(65, 175, 160, 25, "Specular");
      o->type(3);
      o->step(0.001);
      o->callback((Fl_Callback*)cb_specularslider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Value_Slider* o = ambientslider = new Fl_Value_Slider(65, 115, 160, 25, "Ambient");
      o->type(3);
      o->step(0.001);
      o->value(0.2);
      o->callback((Fl_Callback*)cb_ambientslider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Light_Button* o = plot_light_positions = new Fl_Light_Button(120, 5, 105, 25, "Plot Position");
      o->value(1);
      o->callback((Fl_Callback*)cb_plot_light_positions);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Light_Button* o = lightingbutton = new Fl_Light_Button(5, 5, 105, 25, "Do Lighting");
      o->callback((Fl_Callback*)cb_lightingbutton);
    }
    { Fl_Group* o = new Fl_Group(10, 50, 150, 60, "Type");
      o->align(FL_ALIGN_TOP_LEFT);
      { Fl_Round_Button* o = new Fl_Round_Button(15, 55, 25, 25, "Point source");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_Point);
      }
      { Fl_Round_Button* o = new Fl_Round_Button(15, 80, 25, 25, "Directional source");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->value(1);
        o->callback((Fl_Callback*)cb_Directional);
      }
      o->end();
    }
    { Fl_Button* o = new Fl_Button(5, 305, 105, 25, "reset");
      o->callback((Fl_Callback*)cb_reset);
    }
    { Fl_Roller* o = phiroll = new Fl_Roller(100, 210, 125, 25);
      o->type(1);
      o->minimum(-1e+06);
      o->maximum(1e+06);
      o->step(1);
      o->callback((Fl_Callback*)cb_phiroll);
    }
    { Fl_Roller* o = thetaroll = new Fl_Roller(100, 240, 125, 25);
      o->type(1);
      o->minimum(-1e+06);
      o->maximum(1e+06);
      o->step(1);
      o->value(90);
      o->callback((Fl_Callback*)cb_thetaroll);
    }
    { Fl_Roller* o = rroll = new Fl_Roller(100, 270, 125, 25);
      o->type(1);
      o->maximum(2);
      o->step(0.01);
      o->value(1);
      o->callback((Fl_Callback*)cb_rroll);
    }
    { Fl_Value_Output* o = lphival = new Fl_Value_Output(65, 210, 35, 25, "phi");
      o->minimum(-1e+06);
      o->maximum(1e+06);
    }
    { Fl_Value_Output* o = lthetaval = new Fl_Value_Output(65, 240, 35, 25, "theta");
      o->minimum(-1e+06);
      o->maximum(1e+06);
      o->value(90);
    }
    { Fl_Value_Output* o = rval = new Fl_Value_Output(65, 270, 35, 25, "r");
      o->maximum(2);
      o->value(1);
    }
    o->end();
  }
  { Fl_Double_Window* o = imagewindow = new Fl_Double_Window(415, 380);
    w = o;
    { ImageWindow3d* o = iw3d = new ImageWindow3d(0, 0, 415, 385);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  { Fl_Double_Window* o = procwin = new Fl_Double_Window(330, 190, "Image Processing");
    w = o;
    o->color((Fl_Color)29);
    { Fl_Browser* o = options = new Fl_Browser(10, 25, 110, 160, "Options");
      o->type(2);
      o->color((Fl_Color)29);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_ENTER_KEY_ALWAYS);
    }
    { Fl_Browser* o = pqueue = new Fl_Browser(210, 25, 110, 160, "Queue");
      o->type(2);
      o->align(FL_ALIGN_TOP);
    }
    { Fl_Button* o = new Fl_Button(130, 25, 70, 20, "@->  add");
      o->callback((Fl_Callback*)cb_add);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Button* o = new Fl_Button(130, 110, 70, 20, "remove");
      o->callback((Fl_Callback*)cb_remove);
    }
    { Fl_Button* o = new Fl_Button(130, 135, 70, 20, "clear");
      o->callback((Fl_Callback*)cb_clear);
    }
    { Fl_Button* o = new Fl_Button(130, 55, 70, 20, "up @8->");
      o->callback((Fl_Callback*)cb_up);
      o->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    }
    { Fl_Button* o = new Fl_Button(130, 80, 70, 20, "down @2");
      o->callback((Fl_Callback*)cb_down);
      o->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    }
    { Fl_Button* o = new Fl_Button(130, 165, 70, 20, "dismiss");
      o->callback((Fl_Callback*)cb_dismiss1);
    }
    o->end();
  }
  { Fl_Double_Window* o = cmapwin = new Fl_Double_Window(240, 165, "Colormap Controls");
    w = o;
    { Fl_Value_Slider* o = wslider = new Fl_Value_Slider(50, 5, 185, 25, "Width");
      o->type(3);
      o->maximum(4);
      o->step(0.001);
      o->value(1);
      o->callback((Fl_Callback*)cb_wslider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Roller* o = wroller = new Fl_Roller(50, 30, 185, 15);
      o->type(1);
      o->maximum(4);
      o->step(0.001);
      o->callback((Fl_Callback*)cb_wroller);
    }
    { Fl_Value_Slider* o = cslider = new Fl_Value_Slider(50, 55, 185, 25, "Center");
      o->type(3);
      o->minimum(-1);
      o->step(0.001);
      o->callback((Fl_Callback*)cb_cslider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Roller* o = croller = new Fl_Roller(50, 80, 185, 15);
      o->type(1);
      o->minimum(-1);
      o->step(0.001);
      o->callback((Fl_Callback*)cb_croller);
    }
    { Fl_Light_Button* o = new Fl_Light_Button(170, 105, 65, 25, "Invert");
      o->callback((Fl_Callback*)cb_Invert);
    }
    { Fl_Button* o = new Fl_Button(5, 105, 75, 25, "Nomalize");
      o->callback((Fl_Callback*)cb_Nomalize);
    }
    { Fl_Light_Button* o = new Fl_Light_Button(90, 105, 70, 25, "Negate");
      o->callback((Fl_Callback*)cb_Negate);
    }
    { Fl_Button* o = new Fl_Button(5, 135, 230, 25, "dismiss");
      o->callback((Fl_Callback*)cb_dismiss2);
    }
    o->end();
  }
}
