// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef spyview3d_ui_h
#define spyview3d_ui_h
#include <FL/Fl.H>
#include "ImageWindow3d.H"
#include "spyview3d.H"
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *control;
#include <FL/Fl_Choice.H>
extern void filech_cb(Fl_Choice*, void*);
extern Fl_Choice *filech;
extern void cmapch_cb(Fl_Choice*, void*);
extern Fl_Choice *cmapch;
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *greybutton;
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *pointsbutton;
extern Fl_Round_Button *linemeshbutton;
extern Fl_Round_Button *polygonsbutton;
#include <FL/Fl_Button.H>
extern Fl_Button *resetanglebutton;
extern Fl_Button *resetzoombutton;
extern Fl_Button *resettranslatebutton;
extern Fl_Button *resetallbutton;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *psival;
extern Fl_Value_Input *thetaval;
extern Fl_Value_Input *zoomval;
extern Fl_Value_Input *zscaleval;
extern Fl_Value_Input *xtranval;
extern Fl_Value_Input *ytranval;
extern Fl_Light_Button *planeb;
extern Fl_Button *fitplane;
extern Fl_Value_Input *plane_a;
#include <FL/Fl_Slider.H>
extern Fl_Slider *plane_aslider;
#include <FL/Fl_Roller.H>
extern Fl_Roller *plane_aroller;
extern Fl_Value_Input *plane_b;
extern Fl_Slider *plane_bslider;
extern Fl_Roller *plane_broller;
#include <FL/Fl_Input.H>
extern Fl_Input *savebox;
extern void saveb_cb(Fl_Button*, void*);
extern Fl_Button *saveb;
extern Fl_Round_Button *postscriptbutton;
extern Fl_Round_Button *epsbutton;
extern Fl_Round_Button *latexbutton;
extern Fl_Button *show_lighting_controls_window;
extern Fl_Button *dismissb;
extern Fl_Double_Window *lwin;
#include <FL/Fl_Value_Slider.H>
extern Fl_Value_Slider *diffuseslider;
extern Fl_Value_Slider *specularslider;
extern Fl_Value_Slider *ambientslider;
extern Fl_Light_Button *plot_light_positions;
extern Fl_Light_Button *lightingbutton;
extern Fl_Roller *phiroll;
extern Fl_Roller *thetaroll;
extern Fl_Roller *rroll;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *lphival;
extern Fl_Value_Output *lthetaval;
extern Fl_Value_Output *rval;
extern Fl_Double_Window *imagewindow;
extern ImageWindow3d *iw3d;
extern Fl_Double_Window *procwin;
#include <FL/Fl_Browser.H>
extern Fl_Browser *options;
extern Fl_Browser *pqueue;
extern Fl_Double_Window *cmapwin;
extern Fl_Value_Slider *wslider;
extern Fl_Roller *wroller;
extern Fl_Value_Slider *cslider;
extern Fl_Roller *croller;
extern "C" { void make_window(); }
#endif
